### ISSUE TITLE
Self-referencing content type 

### ISSUE THREAD

**Issue by paulpoot** [labd/terraform-provider-contentful#14]
Hey, first of all, thanks for the work you've done developing this. Great to see tooling like this further improve the development experience.

While implementing content types for a project I'm working on, I found that a content type can't reference itself.

Content type (without the irrelevant fields):

```resource "contentful_contenttype" "navigation_collection" {
  field {
    id       = "content"
    name     = "Content"
    type     = "Array"
    items    = {
      type = "Link",
      linkType = "Entry"
    }
    validations = [
      jsonencode({
        linkContentType = [
          contentful_contenttype.navigationCollection.id,
          contentful_contenttype.navigationLink.id
        ]
      })
    ]
  }
}
```

Error:
```
$ terraform apply -var-file=./data.tfvars --auto-approve
contentful_space.{ SPACE }: Refreshing state... [id={ ID }]
contentful_environment.master: Refreshing state... [id=master]
contentful_locale.en-GB: Refreshing state... [id={ ID }]
╷
│ Error: Self-referential block
│
│   on content_types.tf line 115, in resource "contentful_contenttype" "navigation_collection":
│  115:           contentful_contenttype.navigation_collection.id,
│
│ Configuration for contentful_contenttype.navigation_collection may not refer to itself.
╵
╷
│ Error: Self-referential block
│
│   on content_types.tf line 115, in resource "contentful_contenttype" "navigation_collection":
│  115:           contentful_contenttype.navigation_collection.id,
│
│ Configuration for contentful_contenttype.navigation_collection may not refer to itself.
╵
 ```
 
I was wondering if this is a limitation of the provider or the api. It's a bit of an edge case, but it's possible to do the self-reference in the web interface and it'd be great if that could also be done through Terraform.

**Comment by demeyerthom** [comment]
Hi @paulpoot ! I am assuming that my reply will be too late, but no, in the current format such self-referential resources are not possible. To make this work we would have to implement a separate resource that manages these kind of relations. Is this still a feature you require?
