### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by philippeckelintive** [labd/terraform-provider-contentful#18]
Hey there,

first thanks a lot for the work so far on building a Terraform provider for Contentful! 

I just wonder about the current status? Is it still being maintained? 

Looking at the open PR, latest commits etc. I get the impression it is not actively developed anymore, but your active "parent" project [MACH Composer](https://github.com/labd/mach-composer) is using it; i.e. [here](https://github.com/labd/mach-composer/blob/036c453a0567a1b71ca8e9e3f2209bc1e70d72cc/Dockerfile#L92).

Any - short - answer is more than welcome.

Thanks!

**Comment by demeyerthom** [comment]
Hi @philippeckelintive! Apologies for the late reply! 

 The project is not currently maintained. It is also available in the mach composer project because we might start using it again in the future, but there are no immediate plans for that now.
