### ISSUE TITLE
Mistake in Asset resource usage docs

### ISSUE THREAD

**Issue by rahulpatel596** [labd/terraform-provider-contentful#29]
<img width="1422" alt="Screenshot 2024-04-15 at 11 55 56 AM" src="https://github.com/labd/terraform-provider-contentful/assets/33618437/d94a3157-506a-4b80-90d9-0c8f30ef1a6c">

There seems to be a typo in the docs for usage of Asset resource.
Fields.file should look like this
```
file {
   upload = ""
   file_name = ""
   content_type = ""
}
```

**Comment by demeyerthom** [comment]
Updating it. Thanks!
